const TEXT: Record<string, string> = {
  "Attack surface mapping": "攻击面测绘",
  "SCAN": "扫描",
  "RESULTS": "结果",
  "REPORTS": "报告",
  "SCOPE": "范围",
  "LOG": "记录",
  "CONFIG": "配置",
  "CONTROL": "控制",
  "main navigation": "主导航",
  "quick actions": "快捷操作",
  "New Scan": "新建扫描",
  "Enter a target and start.": "输入授权目标后开始检测。",
  "Findings": "漏洞发现",
  "Verified risks and evidence.": "查看已验证风险与证据。",
  "Reports": "报告",
  "Preview and export.": "预览并导出检测报告。",
  "Boundary": "安全边界",
  "Scope": "授权范围",
  "Scope limits and blocked actions.": "查看目标范围、动作限制与拦截记录。",
  "History": "历史记录",
  "Tasks and snapshots.": "查看任务和状态快照。",
  "Settings": "设置",
  "Runtime defaults.": "配置运行参数和默认策略。",
  "Task Console": "任务控制台",
  "Raw task controls.": "高级任务参数与原始事件。",
  "Scan": "扫描",
  "New scan": "新建扫描",
  "Assets": "资产",
  "Console": "控制台",
  "Refresh": "刷新",
  "Stop task": "停止任务",
  "Home": "首页",
  "Welcome to VulnClaw": "欢迎使用 VulnClaw",
  "Idle": "空闲",
  "No target selected": "尚未选择目标",
  "New Scan Task": "新建扫描任务",
  "Clear target": "清空目标",
  "IP/Domain": "IP / 域名",
  "Black IP": "排除 IP",
  "Port": "端口",
  "Custom ports": "自定义端口",
  "Scan mode": "扫描模式",
  "Quick": "快速",
  "Light discovery.": "轻量资产发现。",
  "Standard": "标准",
  "Recommended scan.": "推荐的常规扫描。",
  "Deep": "深度",
  "More checks.": "执行更多安全检查。",
  "Loop": "持续",
  "Repeat scan.": "按周期重复检测。",
  "Resume previous state": "继承上次目标状态",
  "Auto scope": "自动确定范围",
  "Advanced": "高级设置",
  "Hide advanced": "收起高级设置",
  "Start": "开始",
  "Starting": "正在启动",
  "Starting...": "正在启动...",
  "Host": "主机",
  "Path": "路径",
  "Block host": "禁止主机",
  "Block path": "禁止路径",
  "Allow": "允许",
  "Block": "禁止",
  "Action rules": "动作规则",
  "Running": "运行中",
  "Current task": "当前任务",
  "Target": "目标",
  "Recon": "信息收集",
  "Verify": "验证",
  "Report": "报告",
  "View results": "查看结果",
  "View reports": "查看报告",
  "View boundary": "查看边界",
  "Verified": "已验证",
  "Pending": "待确认",
  "Boundary hits": "边界拦截",
  "Snapshot": "快照",
  "Saved": "已保存",
  "Hide raw events": "隐藏原始事件",
  "Show raw events": "显示原始事件",
  "No raw task events yet.": "暂无原始任务事件。",
  "Start deep scan?": "确认启动高强度扫描？",
  "Start scan": "启动扫描",
  "Confirmation required": "需要确认",
  "Confirm": "确认",
  "Cancel": "取消",
  "Close notification": "关闭通知",
  "Quick Recon": "快速侦察",
  "Standard Scan": "标准扫描",
  "Deep Scan": "深度扫描",
  "Verification": "安全验证",
  "Continuous Scan": "持续扫描",
  "Post-exploitation": "后渗透",
  "Queued": "排队中",
  "Completed": "已完成",
  "Failed": "失败",
  "Stopped": "已停止",
  "Candidate": "候选",
  "Manual review": "人工复核",
  "Dismissed": "已忽略",
  "False positive": "误报",
  "Task started": "任务已启动",
  "Task progress": "任务进度",
  "Task message": "任务消息",
  "Task completed": "任务已完成",
  "Task failed": "任务失败",
  "Task stopped": "任务已停止",
  "Critical": "严重",
  "High": "高危",
  "Medium": "中危",
  "Warn": "警告",
  "Low": "低危",
  "Info": "信息",
  "Healthy": "正常",
  "Degraded": "降级",
  "Offline": "离线",
  "Unknown": "未知",
  "Local": "本地",
  "Placeholder": "占位",
  "No phase": "暂无阶段",
  "Custom Scan": "自定义扫描",
  "Default scope": "默认范围",
  "No extra boundary": "无额外边界",
  "Custom boundary": "自定义边界",
  "No resume guidance": "暂无恢复建议",
  "Can end current scan": "可以结束当前扫描",
  "Review verified findings first": "优先复核已验证漏洞",
  "Verify authorization before validation": "验证前确认授权范围",
  "Continue risk discovery": "继续发现风险",
  "Add more recon": "补充信息收集",
  "Resume from current state": "从当前状态继续",
  "Task finished": "任务已完成",
  "Review the risk results or generate a report.": "请查看漏洞结果或生成报告。",
  "Open results": "打开结果",
  "Check advanced logs.": "请检查高级日志。",
  "Open console": "打开控制台",
  "Saved state and reports remain available.": "已保存的状态和报告仍可使用。",
  "Stop request sent": "已发送停止请求",
  "VulnClaw is ending the current task.": "VulnClaw 正在结束当前任务。",
  "Stop current scan?": "确认停止当前扫描？",
  "Stopping will end the current task, but saved state and reports will remain available.": "停止后当前任务将结束，但已保存的状态和报告仍会保留。",
  "Backend unavailable": "后端服务不可用",
  "and open the local address to load the live console.": "，然后打开本地地址加载实时控制台。",
  "Unable to reach the VulnClaw backend API. Start `vulnclaw web` and reconnect.": "无法连接 VulnClaw 后端 API，请检查 Web 服务后重试。",
  "Retry": "重试",
  "Select a target": "选择目标",
  "Back": "返回",
  "« Back": "« 返回",
  "Asset": "资产",
  "Active IP": "活跃 IP",
  "Vulnerability": "漏洞",
  "Hardware": "硬件",
  "Software": "软件",
  "Hardware Vendor": "硬件厂商",
  "Software Vendor": "软件厂商",
  "Generate report": "生成报告",
  "Generating...": "正在生成...",
  "Open reports": "打开报告",
  "Open scope": "打开授权范围",
  "Status": "状态",
  "Report generated": "报告已生成",
  "Format": "格式",
  "Open report": "打开报告",
  "Type": "类型",
  "Evidence": "证据",
  "Impact": "影响",
  "Fix": "修复建议",
  "No structured findings yet.": "暂无结构化漏洞发现。",
  "Waiting": "等待中",
  "Next": "下一步",
  "Resume plan": "恢复计划",
  "Recommended actions": "建议动作",
  "Priority targets": "优先目标",
  "No priority targets.": "暂无优先目标。",
  "Raw data": "原始数据",
  "Collapse": "收起",
  "Expand": "展开",
  "Raw state collapsed.": "原始状态已收起。",
  "No confirmed findings yet": "暂无已确认漏洞",
  "Not summarized yet.": "尚未生成摘要。",
  "Impact needs review.": "影响范围需要复核。",
  "Validate and patch the issue.": "请验证并修复该问题。",
  "Uncategorized": "未分类",
  "Review scope": "复核授权范围",
  "Continue scanning": "继续扫描",
  "Review pending items": "复核待确认项目",
  "No next step is selected yet.": "尚未选择下一步操作。",
  "No reason recorded": "未记录原因",
  "Preferences": "偏好设置",
  "Local UI defaults": "本地界面默认值",
  "Model": "模型",
  "Provider and endpoint": "服务商与接口地址",
  "Scan Policy": "扫描策略",
  "Rounds and runtime": "轮次与运行参数",
  "Data": "数据",
  "Output paths": "输出路径",
  "Scripts": "脚本",
  "Local execution": "本地执行",
  "Diagnostics": "诊断",
  "MCP status": "MCP 状态",
  "Language": "语言",
  "English": "英文",
  "Chinese": "中文",
  "Default scan mode": "默认扫描模式",
  "Default report format": "默认报告格式",
  "Show raw event entry by default": "默认显示原始事件",
  "Local only": "仅保存在本机浏览器",
  "UI preferences are stored in this browser. Runtime settings are saved to the backend.": "界面偏好保存在当前浏览器中，运行参数保存到后端。",
  "Provider": "模型服务商",
  "Base URL": "接口地址",
  "Max rounds": "最大轮次",
  "Rounds per cycle": "每周期轮次",
  "Max cycles": "最大周期数",
  "Show model reasoning output": "显示模型推理输出",
  "MCP services": "MCP 服务",
  "Runnable": "可运行",
  "Tools": "工具",
  "Runtime check": "运行时检查",
  "Default port only": "默认限定端口",
  "Default host only": "默认限定主机",
  "Default path only": "默认限定路径",
  "Default block host": "默认禁止主机",
  "Default block path": "默认禁止路径",
  "Default allow actions": "默认允许动作",
  "Default block actions": "默认禁止动作",
  "Output directory": "输出目录",
  "Enable local script helper": "启用本地脚本助手",
  "Record local script audit": "记录本地脚本审计",
  "Execution guard": "执行防护模式",
  "Safe": "安全",
  "Lab": "靶场",
  "Trusted local": "受信任本机",
  "Max output lines": "最大输出行数",
  "Save preferences": "保存偏好",
  "Save boundary": "保存边界",
  "Save settings": "保存设置",
  "Settings saved.": "设置已保存。",
  "Preferences saved.": "偏好已保存。",
  "Boundary defaults saved.": "默认边界已保存。",
  "Save failed": "保存失败",
  "API key set": "已配置 API Key",
  "No API key": "未配置 API Key",
  "Current scope": "当前授权范围",
  "Defaults": "默认值",
  "Notes": "说明",
  "Boundary watch": "边界监控",
  "Blocked boundary attempts": "已拦截越界尝试",
  "No blocked attempts yet": "暂未发现越界尝试",
  "blocked": "已拦截",
  "Audit hits": "审计命中",
  "High severity": "高危事件",
  "Current high": "当前高危",
  "Rules": "规则",
  "Active task": "活动任务",
  "Saved target": "已保存目标",
  "Add a scope boundary": "请添加授权边界",
  "No explicit host, port, path, or action limits are set.": "尚未设置明确的主机、端口、路径或动作限制。",
  "Scope is clear": "授权范围明确",
  "Target and action boundaries are both defined.": "目标范围和动作边界均已定义。",
  "Boundary is active": "边界已启用",
  "Add action limits for tighter control.": "建议添加动作限制以加强控制。",
  "Add a host, port, or path boundary for precision.": "请添加主机、端口或路径边界。",
  "Set scope on home": "在首页设置范围",
  "No saved default boundary yet.": "尚未保存默认边界。",
  "No extra scope is set for this target.": "该目标尚未设置额外授权范围。",
  "Open settings": "打开设置",
  "Checked every run": "每次执行前检查",
  "Port, host, path, and action limits are revalidated before execution.": "执行前会重新校验端口、主机、路径和动作限制。",
  "Blocked attempts are saved": "保存越界记录",
  "Stops are written to audit data for later review.": "拦截事件会写入审计数据供后续复核。",
  "Deeper runs need tighter scope": "深度任务需要更严格的范围",
  "Deep or continuous modes work best with explicit boundaries.": "深度或持续模式应配置明确边界。",
  "Blocked attempts": "越界拦截",
  "Blocked attempt": "越界尝试",
  "Technical audit": "技术审计",
  "Hide": "隐藏",
  "Show": "显示",
  "By source": "按来源",
  "By rule": "按规则",
  "No source data.": "暂无来源数据。",
  "No rule data.": "暂无规则数据。",
  "No blocked attempts recorded.": "暂无越界拦截记录。",
  "Technical audit hidden.": "技术审计详情已隐藏。",
  "All targets": "全部目标",
  "Tasks": "任务",
  "Targets": "目标",
  "Snapshots": "快照",
  "No task history": "暂无任务历史",
  "0 tasks": "0 个任务",
  "Choose a target to view snapshots.": "请选择目标以查看快照。",
  "No target state": "暂无目标状态",
  "Restore": "恢复",
  "Restoring...": "正在恢复...",
  "Diff": "差异对比",
  "From": "起始快照",
  "To": "目标快照",
  "Select": "选择",
  "Current": "当前",
  "Added findings": "新增漏洞",
  "Updated findings": "更新漏洞",
  "Added steps": "新增步骤",
  "Added assets": "新增资产",
  "None": "无",
  "Loading diff...": "正在加载差异...",
  "Pick snapshots to compare.": "请选择要比较的快照。",
  "Restore snapshot": "恢复快照",
  "File list": "文件列表",
  "Selected": "已选择",
  "No report selected": "尚未选择报告",
  "0 files": "0 个文件",
  "Select a report to preview.": "请选择要预览的报告。",
  "Search": "搜索",
  "target or filename": "目标或文件名",
  "All": "全部",
  "Time": "时间",
  "All time": "全部时间",
  "Today": "今天",
  "Last 7 days": "最近 7 天",
  "No reports yet": "暂无报告",
  "Generate": "生成",
  "No matches": "无匹配结果",
  "Clear filters": "清除筛选",
  "Preview": "预览",
  "Export copy": "导出副本",
  "Open file": "打开文件",
  "Copy path": "复制路径",
  "Report preview": "报告预览",
  "No report selected.": "尚未选择报告。",
  "Task log": "任务记录",
  "Raw command inputs, SSE events, and advanced task parameters.": "配置高级任务参数并查看 SSE 实时事件。",
  "API command: persistent": "API 命令：持续扫描",
  "Asset discovery and public signal collection.": "发现资产并收集公开信号。",
  "Service and entry-point discovery.": "识别服务和入口点。",
  "Verification actions requiring approval.": "执行需要明确授权的验证动作。",
  "Multi-round continuous checks.": "执行多轮持续检查。",
  "Post-exploitation actions, usually blocked.": "后渗透动作，通常应保持禁止。",
  "No explicit allow list": "未设置明确允许列表",
  "No explicit block list": "未设置明确禁止列表",
  "Live event stream": "实时事件流",
  "Command": "命令",
  "Resume target state": "继承目标状态",
  "CVE hint": "CVE 提示",
  "Port only": "限定端口",
  "Host only": "限定主机",
  "Path only": "限定路径",
  "Allow actions": "允许动作",
  "Block actions": "禁止动作",
  "Command hint": "命令提示",
  "verification command, for example id": "验证命令，例如 id",
  "Launch raw task": "启动高级任务",
  "Launching...": "正在启动...",
  "Confirm raw task": "确认高级任务",
  "Launch": "启动",
  "Stop current task": "停止当前任务",
  "Stop": "停止",
  "No tasks yet.": "暂无任务。",
  "No running task.": "当前没有运行中的任务。",
};

const PATTERNS: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
  [/^(\d+) bounds$/, (m) => `${m[1]} 项边界`],
  [/^(\d+) blocked$/, (m) => `已拦截 ${m[1]} 次`],
  [/^(\d+) tasks$/, (m) => `${m[1]} 个任务`],
  [/^(\d+) files$/, (m) => `${m[1]} 个文件`],
  [/^API command: (.+)$/, (m) => `API 命令：${m[1]}`],
  [/^(\d+) verified \/ (\d+) pending$/, (m) => `已验证 ${m[1]} / 待确认 ${m[2]}`],
  [/^Verified (\d+) \/ Pending (\d+)$/, (m) => `已验证 ${m[1]} / 待确认 ${m[2]}`],
  [/^Target: (.+)$/, (m) => `目标：${m[1]}`],
  [/^Action: (.+)$/, (m) => `动作：${m[1]}`],
  [/^Tool: (.+)$/, (m) => `工具：${m[1]}`],
  [/^Phase: (.+)$/, (m) => `阶段：${m[1]}`],
  [/^Task ID: (.+)$/, (m) => `任务 ID：${m[1]}`],
  [/^Command: (.+)$/, (m) => `命令：${m[1]}`],
  [/^Boundary: (.+)$/, (m) => `边界：${m[1]}`],
  [/^Verified findings: (\d+)$/, (m) => `已验证漏洞：${m[1]}`],
  [/^Manual review required: (\d+)$/, (m) => `需要人工复核：${m[1]}`],
  [/^Pending items: (\d+)$/, (m) => `待确认项目：${m[1]}`],
  [/^Scanning (.+)$/, (m) => `正在扫描 ${m[1]}`],
];

function translate(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return value;
  const direct = TEXT[trimmed];
  if (direct) return value.replace(trimmed, direct);
  for (const [pattern, render] of PATTERNS) {
    const match = trimmed.match(pattern);
    if (match) return value.replace(trimmed, render(match));
  }
  return value;
}

function translateElement(element: Element): void {
  if (element.matches("code, pre, script, style")) return;
  for (const attribute of ["placeholder", "title", "aria-label"] as const) {
    const value = element.getAttribute(attribute);
    if (value) element.setAttribute(attribute, translate(value));
  }
  element.childNodes.forEach((node) => {
    if (node.nodeType === Node.TEXT_NODE && node.textContent) {
      node.textContent = translate(node.textContent);
    }
  });
  element.querySelectorAll("*").forEach((child) => translateElement(child));
}

export function enableChineseUi(): () => void {
  document.documentElement.lang = "zh-CN";
  document.title = "VulnClaw 漏洞测试平台";
  translateElement(document.body);
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === "characterData" && mutation.target.textContent) {
        const translated = translate(mutation.target.textContent);
        if (translated !== mutation.target.textContent) mutation.target.textContent = translated;
      }
      mutation.addedNodes.forEach((node) => {
        if (node.nodeType === Node.ELEMENT_NODE) translateElement(node as Element);
        if (node.nodeType === Node.TEXT_NODE && node.textContent) node.textContent = translate(node.textContent);
      });
    }
  });
  observer.observe(document.body, { childList: true, characterData: true, subtree: true });
  return () => observer.disconnect();
}
